permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
# Spend CI time only on latest ref: https://github.com/jonhoo/rust-ci-conf/pull/5
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: Format
jobs:
  fmt_clippy:
    name: Format + Clippy
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        rust: [ stable ]
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
          components: rustfmt, clippy

      - uses: actions/checkout@master

      - name: cargo format + clippy
        run: cargo fmt --all -- --check && cargo clippy --all