on: [push, pull_request]
name: Test
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@master
      - name: Run tests
        run: cargo test --all --all-features --verbose